<?php	return array ( 'SITE_INFO' => array ( 'name' => 'PHP-Amateur通用内容管理系统后台',
 'keyword' => '内容管理系统',
 'description' => '分享自己写的php代码和收藏比较好的php代码，点滴PHP记录提升技术能力', ), 
 'WEB_ROOT' => 'http://127.0.0.1/ms.so/',
 'AUTH_CODE' => 'CdyIlm',
 'ADMIN_AUTH_KEY' => '1239213438@qq.com',
 'DB_HOST' => '127.0.0.1', 'DB_NAME' => 'mingshi',
 'DB_USER' => 'root', 'DB_PWD' => '',
 'DB_PORT' => '3306', 'DB_PREFIX' => 'ms_',
 'webPath' => '/ms.so/', 'TOKEN' => array ( 'admin_marked' => 'QQ群：111', 'admin_timeout' => 7200,
 'member_marked' => 'http://blog.51edm.org', 
 'member_timeout' => 7200, ), );?>